name: Deploy to Azure

on:
  push:
    branches: [main]
  workflow_dispatch:  # Allow manual trigger
    inputs:
      environment:
        description: 'Target environment'
        required: true
        type: choice
        options:
          - production
          - staging

# Ensure only one deployment runs at a time
concurrency:
  group: deployment-${{ github.event.inputs.environment || 'production' }}
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: ${{ github.event.inputs.environment || 'production' }}

    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set environment variables
        run: |
          echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "ACR_NAME=${{ secrets.ACR_NAME }}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ secrets.ACR_NAME }}.azurecr.io/ai-hub-portal:$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Login to Azure Container Registry
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.IMAGE_TAG }}
            ${{ secrets.ACR_NAME }}.azurecr.io/ai-hub-portal:latest
          cache-from: type=registry,ref=${{ secrets.ACR_NAME }}.azurecr.io/ai-hub-portal:cache
          cache-to: type=registry,ref=${{ secrets.ACR_NAME }}.azurecr.io/ai-hub-portal:cache,mode=max

      - name: Deploy to Azure App Service
        run: |
          az webapp config container set \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ secrets.AZURE_APP_SERVICE }} \
            --container-image-name ${{ env.IMAGE_TAG }}

      - name: Restart App Service
        run: |
          az webapp restart \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ secrets.AZURE_APP_SERVICE }}

      - name: Wait for deployment to stabilize
        run: sleep 30

      - name: Health check
        id: health_check
        run: |
          HEALTH_URL="https://${{ secrets.AZURE_APP_SERVICE }}.azurewebsites.net/api/health"
          echo "Checking health at: $HEALTH_URL"

          MAX_RETRIES=10
          RETRY_COUNT=0

          while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
            RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" $HEALTH_URL || echo "000")

            if [ "$RESPONSE" = "200" ]; then
              echo "✓ Health check passed (HTTP 200)"
              curl -s $HEALTH_URL | jq '.'
              exit 0
            fi

            echo "Health check returned HTTP $RESPONSE, retrying in 10s... ($((RETRY_COUNT+1))/$MAX_RETRIES)"
            RETRY_COUNT=$((RETRY_COUNT+1))
            sleep 10
          done

          echo "✗ Health check failed after $MAX_RETRIES attempts"
          exit 1

      - name: Rollback on failure
        if: failure() && steps.health_check.outcome == 'failure'
        run: |
          echo "Health check failed - attempting rollback"

          # Get previous successful tag
          PREVIOUS_TAG=$(az acr repository show-tags \
            --name ${{ secrets.ACR_NAME }} \
            --repository ai-hub-portal \
            --orderby time_desc \
            --top 2 \
            --output tsv | tail -n 1)

          echo "Rolling back to: $PREVIOUS_TAG"

          az webapp config container set \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ secrets.AZURE_APP_SERVICE }} \
            --container-image-name ${{ secrets.ACR_NAME }}.azurecr.io/ai-hub-portal:$PREVIOUS_TAG

          az webapp restart \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ secrets.AZURE_APP_SERVICE }}

      - name: Deployment summary
        if: success()
        run: |
          echo "## Deployment Successful ✓" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Environment**: ${{ github.event.inputs.environment || 'production' }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Image Tag**: ${{ env.GIT_SHA }}" >> $GITHUB_STEP_SUMMARY
          echo "- **App URL**: https://${{ secrets.AZURE_APP_SERVICE }}.azurewebsites.net" >> $GITHUB_STEP_SUMMARY
          echo "- **Health Check**: Passed" >> $GITHUB_STEP_SUMMARY

      - name: Notify on failure
        if: failure()
        run: |
          echo "## Deployment Failed ✗" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Check the logs above for details." >> $GITHUB_STEP_SUMMARY
          echo "If rollback was attempted, verify app is functioning." >> $GITHUB_STEP_SUMMARY
